import type { Metadata } from "next";
import "./globals.css";
import { MovieProvider } from "@/contexts/movie.context";
import { ThemeProvider } from "@/contexts/theme.context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body>
        <ThemeProvider>
          <MovieProvider>
            {/* <Header /> */}
            {children}
          </MovieProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
